/*
 * #%L
 * SUMARiS
 * %%
 * Copyright (C) 2019 SUMARiS Consortium
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge.
//
package net.sumaris.core.model.data;

import lombok.*;
import lombok.ToString;
import lombok.experimental.FieldNameConstants;
import net.sumaris.core.model.IEntity;
import net.sumaris.core.model.referential.QualityFlag;
import net.sumaris.core.model.referential.location.Location;
import net.sumaris.core.model.referential.pmfm.Method;
import net.sumaris.core.model.referential.taxon.ReferenceTaxon;
import net.sumaris.core.model.referential.taxon.TaxonGroup;
import lombok.Getter;
import org.hibernate.annotations.Cascade;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Table technique mettant "à plat" les informations utiles de la table BATCH, a des fins
 * d'optimisation de l'exploitation de ces données.
 * Des champs additionnels sont également calculés dans cette table.
 * ATTENTION : Table technique. (RAZ des données possible).
 * Elle est remplie par le traitement de dénormalisation des lots.
 */
@Getter
@Setter
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@FieldNameConstants
@Entity
@Table(name = "denormalized_batch")
public class DenormalizedBatch  implements IEntity<Integer> {

    @Id
    @EqualsAndHashCode.Include
    private Integer id;

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn(name="id", referencedColumnName="id")
    private Batch batch;

    @Column(length = 40)
    private String label;

    @Column(name = "rank_order", nullable = false)
    private Integer rankOrder;

    @Column(name = "flat_rank_order", nullable = false)
    private Short flatRankOrder;

    @Column(name = "weight")
    private Double weight;

    @Column(name = "indirect_weight")
    private Double indirectWeight;

    @Column(name = "elevate_context_weight")
    private Double elevateContextWeight;

    @Column(name = "indirect_context_weight")
    private Double indirectContextWeight;

    @Column(name = "elevate_weight")
    private Double elevateWeight;

    @Column(name = "individual_count")
    private Integer individualCount;

    // TODO add subgroup_count ?

    @Column(name = "indirect_individual_count")
    private Integer indirectIndividualCount;

    @Column(name = "elevate_individual_count")
    private Integer  elevateIndividualCount;

    /**
     * Nombre d'individus élevé à l'échelle du groupe de taxon, ou par défaut du taxon (cf mantis
     * #37645)
     * Calculé par le traitement de dénormalisation.
     * @return this.taxonElevateIndivCount Integer
     */
    @Column(name = "taxon_elevate_indiv_count")
    private Double taxonElevateIndividualCount;

    /**
     * Poids contextuel élevé à l'échelle du groupe de taxon, ou par défaut du taxon (cf mantis
     * #37645).
     * Calculé par le traitement de dénormalisation.
     */
    @Column(name = "taxon_elevate_context_weight")
    private Double taxonElevateContextWeight;

    /**
     * Poids vif sans élévation reconstitué à partir du poids RTP (cf mantis #30088).
     * Calculé par le traitement de dénormalisation.
     */
    @Column(name = "indirect_rtp_weight")
    private Double indirectRtpWeight;

    /**
     * Poids vif élevé et reconstitué à partir du poids RTP (cf mantis #30088).
     * Calculé par le traitement de dénormalisation.
     */
    @Column(name = "elevate_rtp_weight")
    private Double elevateRtpWeight;

    @Column(name = "sampling_ratio")
    private Double samplingRatio;

    @Column(name = "sampling_ratio_text", length = 50)
    private String samplingRatioText;

    @Column(name = "exhaustive_inventory")
    private Boolean exhaustiveInventory;

    @Column(length = IDataEntity.LENGTH_COMMENTS)
    private String comments;

    @Column(name = "tree_level", nullable = false)
    private Short treeLevel;

    @Column(name = "tree_indent", length = 256)
    private String treeIndent;

    @Column(name = "sorting_values_text", length = 255)
    private String sortingValuesText;

    @Column(name = "is_landing", nullable = false)
    private Boolean isLanding;

    @Column(name = "is_discard", nullable = false)
    private Boolean isDiscard;

    @Column(name = "update_date", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "weight_method_fk")
    private Method weightMethod;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quality_flag_fk", nullable = false)
    private QualityFlag qualityFlag;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inherited_taxon_group_fk")
    private TaxonGroup inheritedTaxonGroup;

    /**
     * L'espèce commerciale déterminée à partir de l'espèce scientifique.
     * Calculé par le traitement de dénormalisation.
     * Dans le cas où le lot ni aucun de ses lots pères indique une espèce commerciale, le
     * traitement détermine la plus forte probalité d'appartenance de l'espèce scientifique à une
     * espèce commerciale.
     * Pour cela, les correspondances existantes entre TAXON_GROUP et REFERENCE_TAXON sont
     * exploitées (cf table TAXON_GROUP_HISTORICAL_RECORD), ou le cas échéant les correspodnances
     * trouvées dans l'arbre d'achantillonnage courant (typiquement dans la "partie retenue" PR, ou
     * les deux types d'espèces une chance d'avoir été déjà saisis).
     * Ce champ sert à afficher le nom commerciale probable, à côté de chaque informations relatifs
     * à une espèce scientifique. C'est le cas par exemple dans les rapports de restitution OBSMER
     * aux professionnels.
     **/
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "calculated_taxon_group_fk")
    private TaxonGroup calculatedTaxonGroup;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "taxon_group_fk")
    private TaxonGroup taxonGroup;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inherited_reference_taxon_fk")
    private ReferenceTaxon inheritedReferenceTaxon;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reference_taxon_fk")
    private ReferenceTaxon referenceTaxon;

    @OneToMany(fetch = FetchType.LAZY, targetEntity = DenormalizedBatch.class, mappedBy = Fields.PARENT, cascade = CascadeType.REMOVE)
    private List<DenormalizedBatch> children = new ArrayList<>();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_batch_fk")
    @ToString.Exclude
    private DenormalizedBatch parent;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "operation_fk")
    @ToString.Exclude
    private Operation operation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sale_fk")
    @ToString.Exclude
    private Sale sale;

    @OneToMany(fetch = FetchType.LAZY, targetEntity = DenormalizedBatchSortingValue.class, mappedBy = DenormalizedBatchSortingValue.Fields.BATCH,
    cascade = CascadeType.REMOVE)
    private List<DenormalizedBatchSortingValue> sortingValues = new ArrayList<>();
}