
export const ErrorCodes = {

  LOAD_REFERENTIAL_ERROR: 10,
  SAVE_REFERENTIAL_ERROR: 11,
  DELETE_REFERENTIAL_ERROR: 12,
  SUBSCRIBE_REFERENTIAL_ERROR: 13,

  LOAD_REFERENTIAL_LEVELS_ERROR: 16,

  LOAD_PROGRAM_PMFMS_ERROR: 17,
  LOAD_PROGRAM_GEARS_ERROR: 18,
  LOAD_PROGRAM_TAXON_GROUPS_ERROR: 19,

  LOAD_VESSELS_ERROR: 301,

  LOAD_PROGRAM_ERROR: 400,
  LOAD_PROGRAMS_ERROR: 401,
  SAVE_PROGRAM_ERROR: 402,
  SAVE_PROGRAMS_ERROR: 402,
  LOAD_STRATEGY_ANALYTIC_REFERENCES_ERROR: 403,
  SUBSCRIBE_AUTHORIZED_PROGRAMS_ERROR: 404,

  IMPORT_REFERENTIAL_ERROR: 500,

  LOAD_SOFTWARE_ERROR: 600,
  SAVE_SOFTWARE_ERROR: 602,

  LOAD_STRATEGY_ERROR: 700,
  LOAD_STRATEGIES_ERROR: 701,
  SAVE_STRATEGY_ERROR: 702

};


