import { ServiceError } from '../../core/services/errors'
export { ServiceError }

export const ErrorCodes = {

  LOAD_REFERENTIAL_ERROR: 10,
  LOAD_REFERENTIAL_ENTITIES_ERROR: 11,
  SAVE_REFERENTIAL_ERROR: 12,
  SAVE_REFERENTIALS_ERROR: 13,
  DELETE_REFERENTIALS_ERROR: 14,
  LOAD_REFERENTIAL_LEVELS_ERROR: 15,
  LOAD_PROGRAM_PMFMS_ERROR: 16,
  LOAD_PROGRAM_GEARS_ERROR: 17,
  LOAD_PROGRAM_TAXON_GROUPS_ERROR: 18,

  LOAD_VESSELS_ERROR: 301,
  SAVE_VESSEL_ERROR: 302,
  SAVE_VESSELS_ERROR: 303,

  LOAD_PROGRAM_ERROR: 400,
  LOAD_PROGRAMS_ERROR: 401,
  SAVE_PROGRAM_ERROR: 402,
  SAVE_PROGRAMS_ERROR: 402,

  IMPORT_REFERENTIAL_ERROR: 500,

  LOAD_SOFTWARE_ERROR: 600,
  SAVE_SOFTWARE_ERROR: 602,

  LOAD_STRATEGY_ERROR: 700,
  LOAD_STRATEGIES_ERROR: 701,
  SAVE_STRATEGY_ERROR: 702

};


