
export const ExtractionErrorCodes = {

  LOAD_EXTRACTION_TYPES_ERROR: 300,
  LOAD_EXTRACTION_ROWS_ERROR: 301,
  DOWNLOAD_EXTRACTION_FILE_ERROR: 302,
  LOAD_EXTRACTION_GEO_TYPES_ERROR: 304,
  LOAD_EXTRACTION_GEO_JSON_ERROR: 305,
  LOAD_EXTRACTION_TECH_ERROR: 306,
  LOAD_EXTRACTION_MIN_MAX_TECH_ERROR: 306,

  UPDATE_PRODUCT_ERROR: 307
};
