-- *****************************************************************
--
-- Insertion des espèces cibles manquantes pour les métier OTB% et OTT%
--
-- *****************************************************************
-- Requête de generation, à executer sur le schéma SIH2_ADAGIO_DBA:
--
-- select CONCAT(
--                CONCAT(
--                        'insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, ''',
--                        CONCAT(
--                                CONCAT(TG.LABEL, ''', '''),
--                                CONCAT(TG.NAME, '''')
--                            )
--                    ),
--                CONCAT(
--                        ' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label=''',
--                        CONCAT(TG.LABEL, ''');'))
--            ) as SQL
-- from METIER M
--          inner join TAXON_GROUP TG on M.TAXON_GROUP_fk = TG.ID
-- where (M.label like 'OTB%' or M.label like 'OTT%')
--   and M.status_fk = 1
-- order by M.LABEL;

insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'ANE', 'Anchois commun' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='ANE');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'BLI', 'Lingue bleue' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='BLI');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'BSE', 'Bars nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='BSE');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CET', 'Céteau' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CET');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'COD', 'Morue (= Cabillaud)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='COD');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CPR', 'Bouquet commun' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CPR');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CSH', 'Crevette grise' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CSH');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CTL', 'Seiches, sépioles nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CTL');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'DCP', 'Crevettes (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='DCP');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, '_DW', 'Poissons de grands fonds' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='_DW');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'ELE', 'Anguille d''Europe' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='ELE');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'FLX', 'Poissons plats' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='FLX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'GAD', 'Gadiformes nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='GAD');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'GUX', 'Grondins (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='GUX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'HER', 'Hareng commun' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='HER');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'HKE', 'Merlu européen' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='HKE');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'IOD', 'Crabe nageur' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='IOD');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'JAX', 'Chinchards (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='JAX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'JOD', 'Saint-Pierre' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='JOD');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MAX', 'Maquereaux (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MAX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MGR', 'Maigre' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MGR');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MNZ', 'Baudroies (= Lottes) (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MNZ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MUL', 'Mulets (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MUL');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MUX', 'Rougets (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MUX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MZZ', 'Poissons' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MZZ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'NEP', 'Langoustine commune' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='NEP');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'OCT', 'Poulpes, Pieuvres, Elédones' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='OCT');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'OST', 'Huîtres (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='OST');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'OYF', 'Huître plate' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='OYF');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'POK', 'Lieu noir' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='POK');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'POL', 'Lieu jaune' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='POL');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'QSC', 'Pétoncle blanc (= Vanneau)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='QSC');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'RAJ', 'Raies (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='RAJ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SAN', 'Lançons (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SAN');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SBG', 'Dorade royale' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SBG');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SBX', 'Dorades, Sparidés' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SBX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SHX', 'Squaliformes nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SHX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SHZ', 'Aloses (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SHZ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SLZ', 'Saumons, Truites' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SLZ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SMX', 'Éperlans nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SMX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SOX', 'Soles (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SOX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SQU', 'Calmars, Encornets' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SQU');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'VSC', 'Pétoncle noir' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='VSC');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'WHG', 'Merlan' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='WHG');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CET', 'Céteau' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CET');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'COD', 'Morue (= Cabillaud)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='COD');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CSH', 'Crevette grise' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CSH');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'CTL', 'Seiches, sépioles nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='CTL');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, '_DW', 'Poissons de grands fonds' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='_DW');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'FLX', 'Poissons plats' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='FLX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'GAD', 'Gadiformes nca' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='GAD');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'HKE', 'Merlu européen' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='HKE');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MNZ', 'Baudroies (= Lottes) (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MNZ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MUX', 'Rougets (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MUX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'MZZ', 'Poissons' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='MZZ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'NEP', 'Langoustine commune' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='NEP');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'QSC', 'Pétoncle blanc (= Vanneau)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='QSC');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'RAJ', 'Raies (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='RAJ');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SOX', 'Soles (divers)' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SOX');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'SQU', 'Calmars, Encornets' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='SQU');
insert into TAXON_GROUP (id, status_fk, creation_date, taxon_group_type_fk, label, name) select NEXT VALUE FOR TAXON_GROUP_SEQ, 1, sysdate, 3, 'VSC', 'Pétoncle noir' FROM STATUS S where S.id=1 and not exists (select * from taxon_group where taxon_group_type_fk=3 and label='VSC');


-- *****************************************************************
--
-- Insertion des métier manquants de type OTB% et OTT%
--
-- *****************************************************************
-- Requête de generation, à executer sur le schéma SIH2_ADAGIO_DBA:
--
-- select CONCAT(
--                CONCAT(
--                        'insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, ''',
--                        CONCAT(
--                                CONCAT(M.LABEL, ''', '''),
--                                CONCAT(M.NAME, ''', ')
--                            )
--                    ),
--                CONCAT(
--                        CONCAT('(SELECT ID FROM GEAR where label=''', G.LABEL),
--                        CONCAT(''') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label=''',
--                               CONCAT(TG.LABEL, ''';'))
--                    )) as SQL
-- from METIER M
--          inner join TAXON_GROUP TG on M.TAXON_GROUP_fk = TG.ID
--          inner join GEAR G on M.GEAR_FK = G.ID
-- where (M.label like 'OTB%' or M.label like 'OTT%')
--   and M.status_fk = 1
-- order by M.LABEL;

insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBANE', 'Chaluts de fond à panneaux (1 Navire) à Anchois commun', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='ANE';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBBLI', 'Chaluts de fond à panneaux (1 Navire) à Lingue bleue', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='BLI';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBBSE', 'Chaluts de fond à panneaux (1 Navire) à Bars nca', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='BSE';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBCET', 'Chaluts de fond à panneaux (1 Navire) à Céteau', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CET';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBCOD', 'Chaluts de fond à panneaux (1 Navire) à Morue (= Cabillaud)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='COD';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBCPR', 'Chaluts de fond à panneaux (1 Navire) à Bouquet commun', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CPR';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBCSH', 'Chaluts de fond à panneaux (1 Navire) à Crevette grise', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CSH';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBCTL', 'Chaluts de fond à panneaux (1 Navire) à Seiches, Sépioles', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CTL';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBDCP', 'Chaluts de fond à panneaux (1 Navire) à Crevettes (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='DCP';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTB_DW', 'Chaluts de fond à panneaux (1 Navire) à Poissons de grands fonds', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='_DW';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBELE', 'Chaluts de fond à panneaux (1 Navire) à Anguille d''Europe', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='ELE';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBFLX', 'Chaluts de fond à panneaux (1 Navire) à Poissons plats', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='FLX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBGAD', 'Chaluts de fond à panneaux (1 Navire) à Gadiformes nca', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='GAD';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBGUX', 'Chaluts de fond à panneaux (1 Navire) à Grondins (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='GUX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBHER', 'Chaluts de fond à panneaux (1 Navire) à Hareng commun', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='HER';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBHKE', 'Chaluts de fond à panneaux (1 Navire) à Merlu européen', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='HKE';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBIOD', 'Chaluts de fond à panneaux (1 Navire) à Crabe nageur', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='IOD';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBJAX', 'Chaluts de fond à panneaux (1 Navire) à Chinchards (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='JAX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBJOD', 'Chaluts de fond à panneaux (1 Navire) à Saint-Pierre', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='JOD';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBMAX', 'Chaluts de fond à panneaux (1 Navire) à Maquereaux (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MAX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBMGR', 'Chaluts de fond à panneaux (1 Navire) à Maigre', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MGR';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBMNZ', 'Chaluts de fond à panneaux (1 Navire) à Baudroies (= Lottes) (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MNZ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBMUL', 'Chaluts de fond à panneaux (1 Navire) à Mulets (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MUL';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBMUX', 'Chaluts de fond à panneaux (1 Navire) à Rougets (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MUX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBMZZ', 'Chaluts de fond à panneaux (1 Navire) à Poissons', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MZZ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBNEP', 'Chaluts de fond à panneaux (1 Navire) à Langoustine commune', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='NEP';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBOCT', 'Chaluts de fond à panneaux (1 Navire) à Poulpes, Pieuvres, Elédones', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='OCT';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBOST', 'Chaluts de fond à panneaux (1 Navire) à Huîtres (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='OST';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBOYF', 'Chaluts de fond à panneaux (1 Navire) à Huîtres plates', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='OYF';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBPOK', 'Chaluts de fond à panneaux (1 Navire) à Lieu noir', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='POK';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBPOL', 'Chaluts de fond à panneaux (1 Navire) à Lieu jaune', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='POL';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBQSC', 'Chaluts de fond à panneaux (1 Navire) à Pétoncle blanc (= Vanneau)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='QSC';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBRAJ', 'Chaluts de fond à panneaux (1 Navire) à Raies (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='RAJ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSAN', 'Chaluts de fond à panneaux (1 Navire) à Lançons (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SAN';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSBG', 'Chaluts de fond à panneaux (1 Navire) à Dorade royale', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SBG';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSBX', 'Chaluts de fond à panneaux (1 Navire) à Dorades, Sparidés', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SBX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSHX', 'Chaluts de fond à panneaux (1 Navire) à Squaliformes nca', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SHX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSHZ', 'Chaluts de fond à panneaux (1 Navire) à Aloses (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SHZ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSLZ', 'Chaluts de fond à panneaux (1 Navire) à Saumons, Truites', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SLZ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSMX', 'Chaluts de fond à panneaux (1 Navire) à Éperlans nca', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SMX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSOX', 'Chaluts de fond à panneaux (1 Navire) à Soles (divers)', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SOX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBSQU', 'Chaluts de fond à panneaux (1 Navire) à Calmars, Encornets', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SQU';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBVSC', 'Chaluts de fond à panneaux (1 Navire) à Pétoncle noir', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='VSC';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTBWHG', 'Chaluts de fond à panneaux (1 Navire) à Merlan', (SELECT ID FROM GEAR where label='OTB') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='WHG';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTCET', 'Chaluts jumeaux à Céteau', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CET';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTCOD', 'Chaluts jumeaux à Morue (= Cabillaud)', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='COD';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTCSH', 'Chaluts jumeaux à Crevette grise', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CSH';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTCTL', 'Chaluts jumeaux à Seiches, Sépioles', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='CTL';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTT_DW', 'Chaluts jumeaux à Poissons de grands fonds', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='_DW';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTFLX', 'Chaluts jumeaux à Poissons plats', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='FLX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTGAD', 'Chaluts jumeaux à Gadiformes nca', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='GAD';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTHKE', 'Chaluts jumeaux à Merlu européen', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='HKE';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTMNZ', 'Chaluts jumeaux à Baudroies (= Lottes) (divers)', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MNZ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTMUX', 'Chaluts jumeaux à Rougets (divers)', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MUX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTMZZ', 'Chaluts jumeaux à Poissons', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='MZZ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTNEP', 'Chaluts jumeaux à Langoustine commune', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='NEP';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTQSC', 'Chaluts jumeaux à Pétoncle blanc (= Vanneau)', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='QSC';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTRAJ', 'Chaluts jumeaux à Raies (divers)', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='RAJ';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTSOX', 'Chaluts jumeaux à Soles (divers)', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SOX';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTSQU', 'Chaluts jumeaux à Calmars, Encornets', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='SQU';
insert into METIER (id, status_fk, creation_date, taxon_group_fk, label, name, gear_fk) select NEXT VALUE FOR METIER_SEQ, 1, sysdate, TG.ID, 'OTTVSC', 'Chaluts jumeaux à Pétoncle noir', (SELECT ID FROM GEAR where label='OTT') FROM TAXON_GROUP TG where taxon_group_type_fk=3 and TG.label='VSC';
