import { TRIP_LOCAL_SETTINGS_OPTIONS } from '@app/trip/services/config/trip.config';

export const TripErrorCodes = {

  UPDATE_OBSERVED_LOCATION_CHILDREN_DATE_ERROR: 248,
  ADD_TRIP_GEAR_ERROR: 249,
  CHILD_OPERATION_NOT_FOUND: 250,
  PARENT_OPERATION_NOT_FOUND: 251
};
