import { ServiceError } from '../../core/services/errors'
export { ServiceError }

export const ErrorCodes = {
  LOAD_TRIP_ERROR: 200,
  LOAD_TRIPS_ERROR: 201,
  SAVE_TRIP_ERROR: 202,
  SAVE_TRIPS_ERROR: 203,
  SUBSCRIBE_TRIP_ERROR: 204,
  CONTROL_TRIP_ERROR: 205,
  VALIDATE_TRIP_ERROR: 206,
  UNVALIDATE_TRIP_ERROR: 207,

  LOAD_OPERATION_ERROR: 210,
  LOAD_OPERATIONS_ERROR: 211,
  SAVE_OPERATION_ERROR: 212,
  SAVE_OPERATIONS_ERROR: 213,
  SUBSCRIBE_OPERATION_ERROR: 214,

  LOAD_SALE_ERROR: 220,
  LOAD_SALES_ERROR: 221,
  SAVE_SALE_ERROR: 222,
  SAVE_SALES_ERROR: 223,
  SUBSCRIBE_SALE_ERROR: 224,

  LOAD_EXTRACTION_TYPES_ERROR: 300,
  LOAD_EXTRACTION_ROWS_ERROR: 301,
  DOWNLOAD_EXTRACTION_FILE_ERROR: 302

};
